/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuMailAttachmentRegistry } from "./QuMailAttachmentRegistry";
export * as factories from "./factories";
export { QuMailAttachmentRegistry__factory } from "./factories/QuMailAttachmentRegistry__factory";
