/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace QuMailAttachmentRegistry {
  export type AttachmentRecordStruct = {
    ipfsCID: string;
    contentSha256: BytesLike;
    keyIdHash: BytesLike;
    securityLevel: BigNumberish;
    timestamp: BigNumberish;
    registeredBy: AddressLike;
  };

  export type AttachmentRecordStructOutput = [
    ipfsCID: string,
    contentSha256: string,
    keyIdHash: string,
    securityLevel: bigint,
    timestamp: bigint,
    registeredBy: string
  ] & {
    ipfsCID: string;
    contentSha256: string;
    keyIdHash: string;
    securityLevel: bigint;
    timestamp: bigint;
    registeredBy: string;
  };
}

export interface QuMailAttachmentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRecord"
      | "isRegistered"
      | "registerAttachment"
      | "totalRegistered"
      | "verifyAttachment"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AttachmentRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAttachment",
    values: [BytesLike, string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttachment",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAttachment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttachment",
    data: BytesLike
  ): Result;
}

export namespace AttachmentRegisteredEvent {
  export type InputTuple = [
    attachmentId: BytesLike,
    ipfsCID: string,
    contentSha256: BytesLike,
    securityLevel: BigNumberish,
    timestamp: BigNumberish,
    registeredBy: AddressLike
  ];
  export type OutputTuple = [
    attachmentId: string,
    ipfsCID: string,
    contentSha256: string,
    securityLevel: bigint,
    timestamp: bigint,
    registeredBy: string
  ];
  export interface OutputObject {
    attachmentId: string;
    ipfsCID: string;
    contentSha256: string;
    securityLevel: bigint;
    timestamp: bigint;
    registeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuMailAttachmentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): QuMailAttachmentRegistry;
  waitForDeployment(): Promise<this>;

  interface: QuMailAttachmentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRecord: TypedContractMethod<
    [_attachmentId: BytesLike],
    [QuMailAttachmentRegistry.AttachmentRecordStructOutput],
    "view"
  >;

  isRegistered: TypedContractMethod<
    [_attachmentId: BytesLike],
    [boolean],
    "view"
  >;

  registerAttachment: TypedContractMethod<
    [
      _attachmentId: BytesLike,
      _ipfsCID: string,
      _contentSha256: BytesLike,
      _keyIdHash: BytesLike,
      _securityLevel: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalRegistered: TypedContractMethod<[], [bigint], "view">;

  verifyAttachment: TypedContractMethod<
    [_attachmentId: BytesLike, _contentSha256: BytesLike],
    [
      [boolean, string, bigint] & {
        isValid: boolean;
        ipfsCID: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [_attachmentId: BytesLike],
    [QuMailAttachmentRegistry.AttachmentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[_attachmentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAttachment"
  ): TypedContractMethod<
    [
      _attachmentId: BytesLike,
      _ipfsCID: string,
      _contentSha256: BytesLike,
      _keyIdHash: BytesLike,
      _securityLevel: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalRegistered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyAttachment"
  ): TypedContractMethod<
    [_attachmentId: BytesLike, _contentSha256: BytesLike],
    [
      [boolean, string, bigint] & {
        isValid: boolean;
        ipfsCID: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AttachmentRegistered"
  ): TypedContractEvent<
    AttachmentRegisteredEvent.InputTuple,
    AttachmentRegisteredEvent.OutputTuple,
    AttachmentRegisteredEvent.OutputObject
  >;

  filters: {
    "AttachmentRegistered(bytes32,string,bytes32,uint8,uint256,address)": TypedContractEvent<
      AttachmentRegisteredEvent.InputTuple,
      AttachmentRegisteredEvent.OutputTuple,
      AttachmentRegisteredEvent.OutputObject
    >;
    AttachmentRegistered: TypedContractEvent<
      AttachmentRegisteredEvent.InputTuple,
      AttachmentRegisteredEvent.OutputTuple,
      AttachmentRegisteredEvent.OutputObject
    >;
  };
}
